// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azkjamiclbxdfjzttkci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6a2phbWljbGJ4ZGZqenR0a2NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3Nzg2MjIsImV4cCI6MjA3MTM1NDYyMn0.6N9BgByDHFYfhcz7753vBRigxtbAisBg6RaXTPRmlHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});